version: '2'
services:
    python-text-search:
        build: .
        container_name: python-text-search
        image: "python-text-search:latest"
        restart: always
        environment:
            - PYTHONPATH=/usr/local/lib/python2.7/site-packages/:/usr/local/lib/python2.7/:/home/igor/app/
            - APPCONF_appPort=8080
            - APPCONF_redisHost=redis
            - APPCONF_redisPort=6379
        depends_on:
            - redis
        ports:
            - 9000:8080

    redis:
        container_name: redis
        image: "redis:latest"
        restart: always
        volumes:
            - /tmp/redis-data
        ports:
            - 7760:6379

