version: '2'
services:
    python-text-search:
        build: .
        container_name: python-text-search
        image: "python-text-search:latest"
        restart: always
        environment:
            - PYTHONPATH=/usr/local/lib/python2.7/site-packages/:/usr/local/lib/python2.7/:/home/igor/app/
            - APPCONF_appPort=80
            - APPCONF_redisHost=redis
            - APPCONF_redisPort=7760
        depends_on:
            - redis
        ports:
            - 9000:80

    redis:
        container_name: redis
        image: "redis:latest"
        restart: always
        ports:
            - 7760:6379

